-- Agency-level seed: team profiles, audit template v1, the 22 SOP records (9 MVP in full).
-- Profile ids match supabase/local/01_users_stub.sql; on Supabase run scripts/seed.ts which maps by email.

insert into public.profiles (id, email, full_name, role) values
  ('00000000-0000-4000-8000-000000000001', 'sako@wavystudios.com', 'Sako Waves', 'admin'),
  ('00000000-0000-4000-8000-000000000002', 'drew@wavystudios.com', 'Andrew (Drew) Lauchner', 'account_lead'),
  ('00000000-0000-4000-8000-000000000003', 'andre@wavystudios.com', 'Andre Stock', 'contributor'),
  ('00000000-0000-4000-8000-000000000004', 'jeanclaude@wavystudios.com', 'Jean-Claude Mouannes', 'account_lead'),
  ('00000000-0000-4000-8000-000000000009', 'outsider@example.com', 'Test Outsider', 'contributor')
on conflict (id) do update set full_name = excluded.full_name, role = excluded.role;

-- ---------- audit template v1 ----------
insert into public.audit_templates (version, areas) values (1, '[
 {"key":"deliverability","name":"Deliverability and list health","weight":10,
  "checks":"SPF/DKIM/DMARC, bounce, spam complaint, unsubscribe rates, sunset policy, suppression hygiene, provider-level opens",
  "source":"Klaviyo deliverability, sending domains, metrics",
  "score1":"DMARC failing or recent domain issue; complaints above 0.1%; no sunset",
  "score5":"All authenticated; complaints under 0.05%; sunset and suppression documented"},
 {"key":"segmentation","name":"Segmentation and audience","weight":15,
  "checks":"Standard segment set exists, definitions correct, exclusions prevent overlap, engagement tiers, never-emailed opted-in contacts",
  "source":"Klaviyo segments, profiles, lists",
  "score1":"Campaigns go to all subscribers; thousands opted in but never emailed",
  "score5":"Named engagement tiers, product affinity, VIP, churn-risk; no idle opted-in contacts"},
 {"key":"flows","name":"Flow coverage and performance","weight":25,
  "checks":"Journey coverage against the standard set, trigger and filter correctness, timing, offer logic, revenue per recipient, share of email revenue from flows",
  "source":"Klaviyo flows and flow report",
  "score1":"Under 6 flows; broken links; flows under 25% of email revenue",
  "score5":"12+ flows covering the journey; flows 50%+ of email revenue; each message above benchmark"},
 {"key":"campaigns","name":"Campaign performance and cadence","weight":15,
  "checks":"Send frequency, revenue per send, open/click/placed-order rates, education-vs-promotion balance, segment usage",
  "source":"Klaviyo campaign report",
  "score1":"Irregular sends; one segment; promotion only",
  "score5":"Consistent calendar; segmented; balanced; top-quartile placed-order rate"},
 {"key":"offers","name":"Offers and economics","weight":10,
  "checks":"Approved offer set, discount depth versus margin, stacking rules, welcome offer, subscription incentive",
  "source":"Facts, Shopify discounts",
  "score1":"No documented offers; discounts ad hoc",
  "score5":"Offer rules approved, margin-checked, tested"},
 {"key":"brand","name":"Brand, copy, and design","weight":10,
  "checks":"Voice consistency with brand and audience, claims compliance, template quality, mobile and dark-mode render, old-brand remnants",
  "source":"Templates, campaigns, facts",
  "score1":"Off-audience voice; old brand name present; unverified claims",
  "score5":"Documented voice; claims list; consistent modules"},
 {"key":"capture","name":"List growth and capture","weight":5,
  "checks":"Form conversion, quiz or pop-up performance, source tracking, welcome handoff, SMS capture",
  "source":"Klaviyo forms report",
  "score1":"One generic pop-up; no tracking",
  "score5":"Tested capture; tracked sources; email and SMS sequence"},
 {"key":"sms","name":"SMS program","weight":10,
  "checks":"Channel role, frequency, compliance, revenue, coordination with email, consent",
  "source":"One Text upload; Klaviyo SMS flows",
  "score1":"SMS run ad hoc by the client; no coordination",
  "score5":"Defined lanes, compliant, coordinated calendar, measured"}
]'::jsonb) on conflict (version) do update set areas = excluded.areas;

-- ---------- SOPs ----------
insert into public.sops (number, name, area, wave, purpose, trigger_text, inputs, steps, decision_rules, output, checklist, owner_role, approval_role, screen, status) values
(1, 'Client onboarding and access', 'Onboarding', 'mvp',
 'Get a client to "ready to operate" with verified access and a complete intake.',
 'Signed SOW',
 '["Signed SOW","Kickoff call transcript","Platform access (Klaviyo, SMS, Shopify, Slack, Figma, Drive)","Client contacts and approvers"]',
 '["Create the client record and assign the pod (Account Lead, Contributor, Admin)","Run the access checklist and record each system as connected / pending / upload / link","Hold the kickoff and import the transcript for fact extraction","Build the stakeholder map: who requests, who approves, who is informed","Record scope and deliverable counts from the SOW as facts","Create the first 30-day plan as the first cycle in draft"]',
 '["No work starts on a platform until its access is verified in the app","Every intake answer becomes a Proposed fact with the kickoff as its source; nothing is Approved on day one"]',
 'Client record, integration status, stakeholder map, first cycle in draft, missing-input list',
 '["SOW uploaded and scope facts proposed","Every integration has a status","Approvers named on both sides","Missing-input list reviewed with the client"]',
 'account_lead', 'admin', 'Client Overview', 'draft'),
(2, 'Source of Truth maintenance', 'Knowledge', 'mvp',
 'Keep client facts verified, sourced, and current so every draft cites approved truth.',
 'New document, transcript, or 90-day review',
 '["Uploaded documents","Transcripts","Platform reads","Decisions from meetings"]',
 '["Agent proposes facts with a source quote","Account Lead verifies against the source","Admin approves offers, voice, pricing, claims, and constraints; Account Lead approves the rest","Set a review date per category","Mark Stale when a source contradicts a fact; re-verify"]',
 '["A fact without a source cannot be Verified","An edit to an Approved fact reopens it as Proposed","Meeting comments become facts only after verification against the transcript"]',
 'Facts with status, source, approver, review date, and version history',
 '["Every Approved fact has a source link and approver","No fact older than its review interval without a check","Sensitive categories approved by an admin"]',
 'account_lead', 'admin', 'Source of Truth', 'draft'),
(3, 'Account health and performance review', 'Measurement', 'mvp',
 'Catch problems and opportunities weekly from platform data.',
 'Nightly job; weekly review by the Account Lead',
 '["Klaviyo flow report (7 and 30 days)","Klaviyo campaign report (7 and 30 days)","List growth","Deliverability metrics","Previous scorecard","Approved objective fact"]',
 '["Pull reports","Compute deltas against the prior period and the audit baseline","Flag anomalies by rule","Draft findings with the report link as evidence","Account Lead confirms, dismisses with reason, or promotes to the backlog"]',
 '["Any live flow with zero sends in 7 days is a finding","Open rate drop over 20% period on period is a finding","Spam complaints above 0.08% or campaign unsubscribe above 0.5% is Severity 1 and goes to the Admin the same day","Flow placed-order rate under half its 90-day average is a finding","Revenue findings are scored impact x confidence / effort"]',
 'Scorecard delta, anomalies, findings',
 '["Every finding has evidence, period, and next action","No number without its source report","Dismissed findings carry a reason"]',
 'account_lead', null, 'Audit', 'draft'),
(4, 'Account audit', 'Strategy', 'mvp',
 'Score the account on a fixed rubric at onboarding and quarterly so trends are comparable.',
 'Onboarding; quarter start',
 '["Audit template v1","Klaviyo reads","Facts","Prior audit"]',
 '["Agent pre-fills scores where data exists","Account Lead scores the rest with evidence and a one-line reason","Create findings per area with severity, confidence, impact, effort","Admin signs off","Promote findings to the opportunity backlog"]',
 '["A score without evidence is saved as Unscored","Severity 1 = fix this week, 2 = this cycle, 3 = backlog","Nightly health review rescores only data-backed areas and never overrides a human score without a finding"]',
 'Scored audit, prioritized findings',
 '["All eight areas scored or marked Unscored","Overall computed from weights","Admin sign-off recorded"]',
 'account_lead', 'admin', 'Audit', 'draft'),
(5, 'Flow audit and rebuild', 'Flows', 'mvp',
 'Document, score, and rebuild lifecycle flows without breaking live sends.',
 'Audit finding; sprint start',
 '["Klaviyo flow inventory","Flow report per message","Approved offer and voice facts","Figma"]',
 '["Sync inventory","Document trigger, filters, exclusions, timing, offer, and links per flow","Check journey coverage against the standard set (welcome, browse, cart, checkout, post-purchase, second purchase, replenishment, winback, sunset, back in stock, VIP, subscription onboarding)","Score each flow on performance, content, technical health","Build the rebuild backlog in priority order","Per flow: brief, Figma, copy, internal review, client approval, build as draft, Admin approves go-live"]',
 '["Never edit a live flow in place; rebuild as a new draft and cut over with a note","Broken links and old-brand references are Severity 1 and fixed immediately","One flow goes live at a time with a 7-day observation window"]',
 'Flow inventory, documented logic, rebuild backlog, proposed changes',
 '["No link to an off-brand domain","No old brand name in copy or alt text","Offer matches an Approved offer fact","Exclusions prevent overlap with campaigns","Test send reviewed on mobile"]',
 'account_lead', 'admin', 'Flows', 'draft'),
(6, 'Two-week campaign planning', 'Campaigns', 'mvp',
 'Turn objective, launches, and backlog into an approved calendar.',
 'Cycle start (every second Monday)',
 '["Objective fact","Launch and inventory facts","Offer rules","Prior cycle results","Send-frequency rule","SMS lane"]',
 '["List fixed events","Set the cycle objective","Allocate slots by purpose with a balance rule","Assign segment and channel per slot","Check inventory and offer eligibility","Submit for Admin approval","Deliver to the client two weeks ahead"]',
 '["Minimum 12 and maximum 16 campaign emails per month once fully transitioned","No promotion two sends in a row","SMS reserved for drops, launches, restocks until frequency rules are approved"]',
 'Approved two-week calendar',
 '["Every slot has segment, channel, purpose, offer status","Launch slots have assets confirmed","No slot conflicts with a live flow offer"]',
 'account_lead', 'admin', 'Calendar', 'draft'),
(7, 'Campaign brief and copy creation', 'Production', 'mvp',
 'Produce a brief and copy from approved facts only.',
 'Calendar slot opened',
 '["Calendar slot","Approved facts (product, claims, voice, offer, audience)","Design references","Prior top performers"]',
 '["Agent drafts the brief: goal, segment, offer, key message, proof, CTA, design notes","Agent drafts 3 subject lines, preview text, body, SMS variant when relevant","Account Lead edits","Version saved","Design handoff"]',
 '["A claim appears only if it maps to an Approved claims fact","Audience language follows the audience fact unless the segment says otherwise","No discount deeper than the approved offer"]',
 'Brief, copy versions, design notes',
 '["Brief fields complete","Facts cited by id","Copy within template limits","CTA links to a live page"]',
 'account_lead', 'account_lead', 'Briefs', 'draft'),
(8, 'Campaign QA and approval', 'Production', 'mvp',
 'Verify brief, copy, links, segments, and offer before client review.',
 'Brief submitted for review',
 '["Brief","Final copy version","Design","Segment definition","Offer code","Test send"]',
 '["Agent runs the checklist pre-check","Reviewer checks links, personalization, offer code, segment count, exclusions, mobile render, dark mode, legal footer, unsubscribe link","Admin internal approval on the version","Client approval requested with the Figma link","Slack permalink recorded","Status set to Client approved"]',
 '["Any failed item blocks approval","An edit after approval resets to Draft","Client silence is not approval"]',
 'QA checklist result, internal approval, client approval evidence',
 '["Links resolve","Personalization fallbacks set","Offer code valid and matches the approved offer","Segment count sane and exclusions applied","Mobile render checked","Dark mode checked","Legal footer present","Unsubscribe link works","Subject and preview reviewed","Claims map to approved facts","Design matches brief","Send time matches calendar"]',
 'account_lead', 'admin', 'Briefs', 'draft'),
(9, 'Biweekly meeting prep and follow-through', 'Client management', 'mvp',
 'Run the client meeting on evidence and close every commitment.',
 '48 hours before the meeting; meeting end',
 '["Scorecard","Completed work","Open decisions","Prior commitments","Next cycle plan"]',
 '["Agent drafts the pre-read 48 hours before","Account Lead edits","Admin sends","Meeting held","Decisions and commitments recorded within 24 hours with owner and due date","Commitments mirrored to ClickUp","Prior commitments reconciled at the next prep"]',
 '["A decision that changes an Approved fact triggers SOP 2","A commitment without an owner cannot be saved"]',
 'Pre-read, agenda, decisions, commitments',
 '["Pre-read under two pages","Every number sourced","Every open decision has options","Every commitment has an owner and date"]',
 'account_lead', 'admin', 'Meeting', 'draft'),
(10, 'Segmentation and audience architecture', 'Strategy', 'phase2', 'Standard segment set, naming, validation.', 'Onboarding; quarterly', '[]', '[]', '[]', 'Segment map, validation log', '[]', 'account_lead', null, 'Strategy', 'draft'),
(11, 'Deliverability, consent, and list health', 'Measurement', 'phase2', 'Authentication, suppression, sunset, incident response.', 'Monthly; anomaly', '[]', '[]', '[]', 'Health report, suppression decisions', '[]', 'account_lead', 'admin', 'Reporting', 'draft'),
(12, 'Offers and merchandising rules', 'Knowledge', 'phase2', 'Approved offer types, limits, stacking, exclusions.', 'Client approves an offer', '[]', '[]', '[]', 'Offer facts', '[]', 'admin', 'admin', 'Source of Truth', 'draft'),
(13, 'Brand voice and copy standards', 'Knowledge', 'phase2', 'Voice principles, vocabulary, prohibited language, claims review.', 'Onboarding; rebrand', '[]', '[]', '[]', 'Voice facts, examples', '[]', 'admin', 'admin', 'Source of Truth', 'draft'),
(14, 'Design and creative system', 'Production', 'phase2', 'Modules, templates, mobile hierarchy, dark mode, asset organization.', 'Onboarding; rebrand', '[]', '[]', '[]', 'Design reference set', '[]', 'contributor', 'account_lead', 'Briefs', 'draft'),
(15, 'SMS program', 'Campaigns', 'phase2', 'Channel role, frequency, compliance, coordination with email.', 'Onboarding', '[]', '[]', '[]', 'SMS rules, calendar lane', '[]', 'account_lead', null, 'Calendar', 'draft'),
(16, 'List growth and capture', 'Strategy', 'phase2', 'Pop-up strategy, offers, welcome handoff, testing.', 'Quarterly', '[]', '[]', '[]', 'Capture plan, test log', '[]', 'account_lead', null, 'Strategy', 'draft'),
(17, 'Experimentation and learning', 'Measurement', 'phase2', 'Hypothesis, test design, evaluation, rollout.', 'Any test', '[]', '[]', '[]', 'Experiment record, learning', '[]', 'account_lead', null, 'Reporting', 'draft'),
(18, 'Monthly reporting and diagnosis', 'Measurement', 'phase2', 'Metric dictionary, attribution caveats, driver explanation.', 'Month end', '[]', '[]', '[]', 'Monthly report', '[]', 'account_lead', 'admin', 'Reporting', 'draft'),
(19, 'CRO and onsite alignment', 'Strategy', 'phase2', 'Message-to-page consistency, onsite test backlog, handoffs.', 'Audit; launch', '[]', '[]', '[]', 'Onsite backlog', '[]', 'account_lead', null, 'Strategy', 'draft'),
(20, 'Client communication and escalation', 'Client management', 'phase2', 'Update cadence, intake, scope change, delays.', 'Ongoing', '[]', '[]', '[]', 'Communication log', '[]', 'account_lead', 'admin', 'Client Overview', 'draft'),
(21, 'Quarterly planning and roadmap', 'Strategy', 'phase3', 'Goal review, opportunity sizing, 30/60/90.', 'Quarter start', '[]', '[]', '[]', 'Roadmap', '[]', 'admin', 'admin', 'Strategy', 'draft'),
(22, 'Knowledge maintenance and offboarding', 'Knowledge', 'phase3', 'Stale review, SOP updates, access review, handoff.', 'Quarterly; contract end', '[]', '[]', '[]', 'Review log, offboarding checklist', '[]', 'admin', 'admin', 'Playbook', 'draft')
on conflict (number) do update set name = excluded.name, purpose = excluded.purpose, trigger_text = excluded.trigger_text,
  inputs = excluded.inputs, steps = excluded.steps, decision_rules = excluded.decision_rules, output = excluded.output,
  checklist = excluded.checklist, owner_role = excluded.owner_role, approval_role = excluded.approval_role, screen = excluded.screen;
