-- Atrakt: SOW facts and a generic claims list drafted from atrakt.com product pages (2026-10-08).
-- All Proposed. Claims need legal/compliance review before an admin approves them.

insert into public.sources (id, client_id, kind, title, url, captured_at, uploaded_by) values
 ('20000000-0000-4000-8000-000000000006', '10000000-0000-4000-8000-000000000001', 'contract', 'Atrakt SOW — Lifecycle Retention Marketing (Tier 1)', null, '2026-10-08', '00000000-0000-4000-8000-000000000001'),
 ('20000000-0000-4000-8000-000000000007', '10000000-0000-4000-8000-000000000001', 'link', 'atrakt.com product pages (ingredients, descriptions)', 'https://www.atrakt.com/collections/all', '2026-10-08', '00000000-0000-4000-8000-000000000001')
on conflict (id) do nothing;

with s as (select '10000000-0000-4000-8000-000000000001'::uuid c, '20000000-0000-4000-8000-000000000006'::uuid sow, '20000000-0000-4000-8000-000000000007'::uuid site, '00000000-0000-4000-8000-000000000001'::uuid sako)
insert into public.facts (client_id, category, statement, status, source_id, source_quote, proposed_by_kind, proposed_by, review_due)
select c, cat::app.fact_category, stmt, 'proposed', case src when 'sow' then sow else site end, quote, 'user', sako, due::date
from s, (values
 -- SOW
 ('business_objective', 'Engagement: Lifecycle Retention Marketing, Tier 1, custom price $6,500 per month; onboarding fee voided.', 'sow', 'Monthly | Lifecycle Retention Marketing: TIER 1 | CUSTOM PRICE: $6,500', '2027-01-15'),
 ('business_objective', 'SOW primary objectives: email acquisition (list growth), design (mobile/conversion, new master template), flows (revenue foundation), advanced segmentation, campaigns across more content pillars matching the customer journey.', 'sow', 'Primary Objectives — Email Acquisition; Design; Flows; Segmentation; Campaigns', '2027-01-15'),
 ('business_objective', 'The SOW states no revenue target; the figures from the Sept 17 call ($200k/month, $250k additional, 20% = $2M/year) are not contractual.', 'sow', 'No revenue commitment appears in the SERVICES + FEE SUMMARY', '2027-01-15'),
 ('constraints_rules', 'Month 1 scope: flow rebuilds and foundational setup; campaign calendar for the next month is established at end of month 1.', 'sow', 'Month 1: Flow Rebuilds, foundational setup, end of month establish campaign calendar for next month', '2026-11-15'),
 ('constraints_rules', 'Month 2+ scope: 2–3 campaigns per week; A/B test one flow per month on subject lines, copy, or offer.', 'sow', 'Month 2+: Campaigns 2-3 campaigns/week, A/B Test 1 Flow monthly', '2027-01-15'),
 ('constraints_rules', 'Contracted flow set: Welcome, Abandoned Checkout, Post-Purchase, Replenishment, Site Abandonment, Cross-sell/Upsell, Review Requests; Layer 2: Second purchase, Add to cart, Back in stock, VIP, Sunset; segmentation leads → first-time → repeat → lapsed.', 'sow', 'Email Marketing Flows row', '2027-01-15'),
 ('constraints_rules', 'Contracted foundation: Klaviyo–Shopify integration, UTM tracking, advanced segmentation, base templates (desktop, mobile, dark mode), customer avatar research, pop-up forms with better incentives (e.g. gift with purchase vs discounts).', 'sow', 'Email Marketing Foundation row', '2027-01-15'),
 ('constraints_rules', 'Contracted reporting: retention-focused (RPE, LTV, churn, campaign vs flow attribution) with biweekly strategy meetings.', 'sow', 'Analytics & Reporting row', '2027-01-15'),
 ('constraints_rules', 'SMS is in scope for product drops, restocks, and high-urgency events, integrated with the email calendar.', 'sow', 'Integration of SMS for product drops, restocks, and high-urgency events', '2027-01-15'),
 ('offers_discounts', 'SOW guidance: prefer gift-with-purchase style incentives over discounts for capture; reduce reliance on discounts.', 'sow', 'better incentives (e.g., gift with purchase vs. discounts) ... reducing reliance on discounts', '2027-01-15'),
 -- Catalog (site, Oct 8 2026)
 ('products_launches', 'Live catalog on atrakt.com: D-BLOAT ($29.99, powder, 3 variants), D-BLOAT LYTE ($29.99), DEBLOAT PROTOCOL bundle ($49.99), B-CLEAR ($29.99, capsules), C-VOLUME ($29.99), U-GLOW ($29.99, gummies), Z-MODE sleep gummies ($29.99), HAIR + SKIN PROTOCOL bundle ($49.99), D-BLOAT and B-CLEAR guides ($14.99), Shipping Protection ($1.99–2.42).', 'site', 'products.json 2026-10-08', '2026-11-08'),
 ('products_launches', 'Z-MODE (the "sleep gummy") is live on the site: magnesium glycinate 100 mg, L-theanine 200 mg, GABA 150 mg, lemon balm 100 mg; no melatonin.', 'site', 'Z-MODE product page', '2026-11-08'),
 -- Claims list: product by product. Pattern: allowed structure/function language taken from the site; prohibited = disease/drug framing.
 ('claims_compliance', 'CLAIMS FRAMEWORK (generic, drafted from site copy; needs compliance review): use structure/function language only ("supports", "helps maintain", "promotes"); never claim to treat, cure, prevent, or diagnose any disease or condition (acne, hair loss, insomnia, edema); no before/after outcome guarantees; carry the FDA disclaimer wherever a claim appears; products labelled 18+.', 'site', 'Derived from product pages; FDA disclaimer text was not detected in the page copy fetched on 2026-10-08 — verify it is present in the footer/labels', '2027-01-15'),
 ('claims_compliance', 'D-BLOAT allowed: "reduce bloating and water retention", "support healthy fluid balance and digestion", "feel lighter". Ingredients: vitamin C 245 mg, magnesium 100 mg, potassium 425 mg (chloride form), chloride 448 mg, dandelion root 375 mg, nettle leaf 175 mg, hibiscus 175 mg, juniper berry 100 mg, horsetail 200 mg. Avoid: "diuretic" as a drug claim, "flush toxins", weight-loss claims, "facial definition" as a guaranteed result.', 'site', 'D-BLOAT product page', '2027-01-15'),
 ('claims_compliance', 'D-BLOAT LYTE allowed: "daily electrolyte powder", "supports hydration and healthy fluid balance", "helps counter excess dietary sodium", "supports digestion". Ingredients: vitamin C 250 mg, potassium 1,000 mg, sodium 150 mg, magnesium 75 mg, dandelion root 200 mg, digestive enzymes. Avoid: comparisons that name competitors (coconut water brands, Liquid IV) in client-facing copy unless approved.', 'site', 'D-BLOAT LYTE product page', '2027-01-15'),
 ('claims_compliance', 'Z-MODE allowed: "supports deeper, more restorative sleep", "helps calm the mind and relax the body", "melatonin-free". Avoid: "treats insomnia", "sedative", sleep-duration guarantees.', 'site', 'Z-MODE product page', '2027-01-15'),
 ('claims_compliance', 'C-VOLUME allowed: "supports stronger, fuller-looking hair", "helps reduce shedding", "supports healthy hair growth", "supports healthy DHT levels". Ingredients: saw palmetto 160 mg, pumpkin seed 100 mg, L-cysteine 75 mg, bamboo (silica) 50 mg, grape seed 75 mg. Avoid: "regrows hair", "treats hair loss / alopecia", "DHT blocker" as a drug claim.', 'site', 'C-VOLUME product page', '2027-01-15'),
 ('claims_compliance', 'U-GLOW allowed: "supports natural radiance", "supports even skin tone", "antioxidant support". Ingredients: lycopene 30.9 mg, astaxanthin 12.7 mg, beta-carotene 975 mcg, vitamin E 84.4 mg. Avoid: "tanning pill", "sun protection / replaces sunscreen", "reduces fine lines" as a drug claim.', 'site', 'U-GLOW product page', '2027-01-15'),
 ('claims_compliance', 'B-CLEAR allowed: "supports clear, balanced skin", "helps regulate oil production", "supports the skin barrier". Ingredients: vitamin A 1,200 mcg, niacinamide 300 mg, pantothenic acid 300 mg, zinc 18 mg, chromium 250 mcg. Avoid: "treats acne", "reduces acne severity" (acne is a disease claim), "antibacterial", "clears breakouts in X days".', 'site', 'B-CLEAR product page — the page itself says "reduce acne severity", which is a disease claim; flag for the client', '2027-01-15'),
 ('claims_compliance', 'Bundles (DEBLOAT PROTOCOL, HAIR + SKIN PROTOCOL) inherit each component''s allowed claims; describe as "routine" or "protocol", not "treatment".', 'site', 'Bundle product pages', '2027-01-15')
) v(cat, stmt, src, quote, due);
